name: 🚀 deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Install Vercel CLI
        run: bun install -g vercel@latest

      - name: 🚀 Deploy to Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
